### PR TITLE
Gofmt and formatting tweaks

### PR DESCRIPTION
**Pull request by dchest**

### CODE REVIEW

**Comment by bkaradzic** [comment]
LGTM, but I'm letting @dgryski check this first.

**Comment by dchest** [comment]
Diff is so large because converted CR+LF to LF (I think that's the only thing it's done, actually:)

**Comment by dgryski** [comment]
I had been not wanting to lose line history by having a massive white space fix to change the line endings. In the long run though it doesn't matter and this should just be merged.

**Comment by dgryski** [comment]
Btw, to see a diff ignoring white space, append `?w=1`  :https://github.com/StableLib/lz4/commit/baf15f99c495327faf99bf43e5f83023dece8137?w=1

**Comment by dchest** [comment]
@dgryski nice, thanks for the tip.

**Pull request merged**
